# Generated by Django 5.1.4 on 2025-01-05 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('pacientes', '0002_alter_pacientes_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='pacientes.pacientes'),
        ),
    ]
