# Generated by Django 5.1.4 on 2025-01-05 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemHistorico',
            fields=[
                ('id_imagem_historico', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=models.AutoField(primary_key=True, serialize=False))),
                ('id_historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='historicos.historico')),
            ],
        ),
    ]
